import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Carousel from '../components/Carousel'

const inter = Inter({ subsets: ['latin'] })

export default function Ourstory() {
  return (
    <>
      <Head>
        <title>Our Story</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <div className="w-full">
           <Image 
            src="/Banner4.png"
            alt="Picture of the author"
            width={1920}
            height={1080}
            layout="responsive"
            />  
            <div className='container mx-auto p-8 flex justify-center flex-wrap'>
            <h1 className='text-2xl tracking-widest py-4 pt-8'>Our Story</h1>
            <p className='py-4 text-center text-sm'>I{`'`}m a paragraph. Click here to add your own text and edit me. It’s easy. Just click “Edit Text” or double click me and you can start adding your own content and make changes to the font. Feel free to drag and drop me anywhere you like on your page. I’m a great place for you to tell a story and let your users know a little more about you.</p>
            <p className='pb-12 text-center text-sm'>​This is a great space to write long text about your company and your services. You can use this space to go into a little more detail about your company. Talk about your team and what services you provide. Tell your visitors the story of how you came up with the idea for your business and what makes you different from your competitors. Make your company stand out and show your visitors who you are.</p>
           
            </div>
           </div>
  
      </main>
    </>
  )
}
