import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Carousel from './components/Carousel'
import Carousel2 from './components/Carousel/Carousel'
import Newarrivals from './components/Newarrivals'
import Footer from './components/Layouts/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Carousel/>
      <Newarrivals/>
      </main>

      
    </>
  )
}
