import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Newarrivals from '../components/Newarrivals'
import Products from '../components/Products'
import Filter from '../components/Filter'

const inter = Inter({ subsets: ['latin'] })

export default function Shopcollection() {
  return (
    <>
      <Head>
        <title>Shop Collection</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=""> 
      <div className="container mx-auto p-4 md:w-10/12 w-96 flex justify-center">
          <div className='grid grid-cols-1 gap-4'>
          <div className='flex justify-center'><h1 className='text-2xl tracking-widest '>Shop Collection</h1></div>
          <div className="grid grid-cols-6">
          <div className='hidden md:hidden lg:block'><Filter/></div>

          <div className='md:col-span-6 lg:col-span-5 col-span-6'>          
          <div className="grid md:grid-cols-3 gap-4">
                    <div><Products/></div>
                    <div><Products/></div>
                      <div><Products/></div>
                      <div><Products/></div>
                        <div><Products/></div>
                        <div><Products/></div>

                        <div><Products/></div>
                        <div><Products/></div>
                        <div><Products/></div>
                        <div><Products/></div>
                        <div><Products/></div>
                        <div><Products/></div>
                      
                  </div>
            </div>
          </div>
          </div>
        </div>
      </main>
    </>
  )
}
